import { useEffect, useState } from 'react';
import { api } from '../lib/api.js';
import { toast } from '../components/Toast.jsx';
import PayModal from '../components/PayModal.jsx';

const LABELS = { pending:'待客服评估', needs_info:'待补充信息', awaiting_customer:'待您确认', payment_pending:'待付款', in_progress:'处理中', completed:'已完成', rejected:'不予受理', withdrawn:'已撤回' };

export default function ServiceChanges() {
  const [data, setData] = useState({ orders:[], changes:[] }); const [form,setForm]=useState({source_order_id:'',request_summary:'',requested_deadline:''}); const [busy,setBusy]=useState(false); const [pay,setPay]=useState(null);
  const load=()=>api.listServiceChanges().then(setData).catch(e=>toast.error(e.message)); useEffect(()=>{load();},[]);
  const submit=async()=>{setBusy(true);try{await api.createServiceChange({...form,source_order_id:Number(form.source_order_id)});toast.success('变更申请已提交，客服会评估是否套餐内或需要补款');setForm({source_order_id:'',request_summary:'',requested_deadline:''});load();}catch(e){toast.error(e.message);}finally{setBusy(false);}};
  const confirm=async(change)=>{setBusy(true);try{const result=await api.confirmServiceChange(change.id);if(result.free){toast.success('已确认，客服将按套餐内变更处理');load();}else setPay(result);}catch(e){toast.error(e.message);}finally{setBusy(false);}};
  return <div className="mx-auto max-w-5xl px-6 py-8"><h1 className="text-xl font-bold text-ink">需求变更与补款</h1><p className="mt-1 text-sm text-slate-500">已付款项目需要增加范围、交付物或修改次数时，请在这里提交。客服先评估，您确认后才会产生补款。</p>
    <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-ink">新建变更申请</h2><div className="mt-4 grid gap-4"><label className="text-sm">关联已付款服务<select className="input mt-1" value={form.source_order_id} onChange={e=>setForm({...form,source_order_id:e.target.value})}><option value="">请选择</option>{data.orders.map(o=><option key={o.id} value={o.id}>{o.order_no} · {o.target_name}</option>)}</select></label><label className="text-sm">新增或调整的具体需求<textarea className="input mt-1" rows="4" maxLength="3000" value={form.request_summary} onChange={e=>setForm({...form,request_summary:e.target.value})} placeholder="请写清新增内容、交付格式、数量、修改次数等" /></label><label className="text-sm">期望完成时间（选填）<input className="input mt-1" value={form.requested_deadline} onChange={e=>setForm({...form,requested_deadline:e.target.value})} /></label></div><div className="mt-4 flex justify-end"><button className="btn-primary" disabled={busy||!form.source_order_id||!form.request_summary.trim()} onClick={submit}>提交客服评估</button></div></div>
    <div className="mt-6 space-y-3">{data.changes.map(c=><div className="rounded-xl border border-slate-200 bg-white p-5" key={c.id}><div className="flex flex-wrap justify-between gap-3"><div><div className="font-medium text-ink">{c.change_no} · {c.source_name}</div><div className="mt-1 text-xs text-slate-400">原订单 {c.source_order_no}</div></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs">{LABELS[c.status]||c.status}</span></div><div className="mt-3 text-sm text-slate-600">{c.request_summary}</div>{c.support_note&&<div className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><b>客服说明：</b>{c.support_note}</div>}{c.change_scope&&<div className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-900"><b>客服处理范围：</b>{c.change_scope}{c.quote_exclusions&&<div className="mt-1 text-xs">不包含：{c.quote_exclusions}</div>}</div>}{c.assessment_type==='chargeable'&&<div className="mt-3 font-semibold text-accent">补款金额 ¥{(c.amount_cents/100).toFixed(2)}</div>}{c.status==='awaiting_customer'&&<button className="btn-primary mt-4" disabled={busy} onClick={()=>confirm(c)}>{c.assessment_type==='included'?'确认套餐内变更':'确认范围并补款'}</button>}</div>)}{!data.changes.length&&<div className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-400">暂无变更单</div>}</div>
    {pay&&<PayModal order={pay.order} payParams={pay.payParams} onClose={()=>setPay(null)} onPaid={()=>{setPay(null);load();}} />}
  </div>;
}
