import { useEffect, useState } from 'react';
import { api } from '../../lib/api.js';
import { toast } from '../../components/Toast.jsx';
import { Refresh } from '../../components/Icons.jsx';

export default function AdminPromotion(){
  const [data,setData]=useState({partners:[],codes:[]}); const [partner,setPartner]=useState(''); const [code,setCode]=useState(''); const [partnerId,setPartnerId]=useState('');
  const load=async()=>{try{setData(await api.adminPromotion());}catch(e){toast.error(e.message);}}; useEffect(()=>{load();},[]);
  const addPartner=async()=>{try{await api.adminCreatePromotionPartner({name:partner});setPartner('');await load();toast.success('推广方已创建');}catch(e){toast.error(e.message);}};
  const addCode=async()=>{try{await api.adminCreatePromotionCode({code,partner_id:Number(partnerId)});setCode('');await load();toast.success('推广码已创建');}catch(e){toast.error(e.message);}};
  return <div className="mx-auto max-w-5xl px-6 py-8"><div className="flex justify-between"><div><h1 className="text-xl font-bold text-ink">推广渠道</h1><p className="mt-1 text-sm text-slate-500">管理推广码并查看项目、成交数量和成交金额；结算仍由线下完成。</p></div><button className="btn-ghost" onClick={load}><Refresh className="h-4 w-4"/>刷新</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="card p-5"><h2 className="font-semibold">新增推广方</h2><div className="mt-3 flex gap-2"><input className="input" value={partner} onChange={e=>setPartner(e.target.value)} placeholder="推广方名称"/><button className="btn-primary" onClick={addPartner}>添加</button></div></div><div className="card p-5"><h2 className="font-semibold">新增推广码</h2><div className="mt-3 flex gap-2"><input className="input uppercase" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="推广码"/><select className="input" value={partnerId} onChange={e=>setPartnerId(e.target.value)}><option value="">选择推广方</option>{data.partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="btn-primary" onClick={addCode}>添加</button></div></div></div><div className="mt-6 overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">推广码</th><th className="p-3">推广方</th><th className="p-3">项目数</th><th className="p-3">成交数</th><th className="p-3">成交金额</th><th className="p-3">状态</th></tr></thead><tbody>{data.codes.map(c=><tr key={c.id} className="border-t"><td className="p-3 font-mono">{c.code}</td><td className="p-3">{c.partner_name}</td><td className="p-3">{c.project_count}</td><td className="p-3">{c.paid_count}</td><td className="p-3">¥{Number(c.paid_amount||0).toFixed(2)}</td><td className="p-3"><button className="btn-ghost text-xs" onClick={async()=>{await api.adminSetPromotionCode(c.id,!c.is_active);await load();}}>{c.is_active?'停用':'启用'}</button></td></tr>)}</tbody></table>{!data.codes.length&&<div className="p-8 text-center text-sm text-slate-400">暂无推广码</div>}</div></div>;
}
