import { useEffect, useRef, useState } from 'react';
import { api } from '../lib/api.js';
import { toast } from './Toast.jsx';
import { Check, FileText, Refresh } from './Icons.jsx';

const STATUS = [['submitted','已提交'],['evaluating','评估中'],['awaiting_quote','待报价'],['awaiting_payment','待付款'],['paid','已付款'],['in_progress','进行中'],['waiting_customer','待用户补充'],['pending_acceptance','待验收'],['revision','修改中'],['completed','已完成'],['cancelled','已取消'],['refunded','已退款']];
const money = cents => `¥${(Number(cents || 0) / 100).toFixed(2)}`;

export default function StaffServiceProjects({ scope, readOnly = false }) {
  const fileRef = useRef(null);
  const [list, setList] = useState([]), [selected, setSelected] = useState(null), [busy, setBusy] = useState(false), [filter, setFilter] = useState('');
  const [form, setForm] = useState({ status:'', progress:0, stage:'', next_action:'', user_visible_note:'', internal_note:'', eta_at:'', scope_summary:'', estimated_hours:0, actual_hours:0, internal_cost_yuan:0 });
  const [delivery, setDelivery] = useState({ milestone_id:'', version_label:'', description:'', is_preview:false });
  const load = async () => { try { setList((await api.staffListServiceProjects(scope, { status: filter })).projects || []); } catch(e) { toast.error(e.message); } };
  useEffect(() => { load(); }, [filter]);
  const open = async id => { try { const p=(await api.staffServiceProjectDetail(scope,id)).project; const date=p.eta_at?new Date(Number(p.eta_at)*1000):null; const offset=date?date.getTimezoneOffset()*60000:0; setSelected(p); setForm({status:p.status,progress:p.progress,stage:p.stage,next_action:p.next_action,user_visible_note:'',internal_note:p.internal_note||'',eta_at:date?new Date(date.getTime()-offset).toISOString().slice(0,16):'',scope_summary:p.scope_summary||'',estimated_hours:Number(p.estimated_hours||0),actual_hours:Number(p.actual_hours||0),internal_cost_yuan:Number(p.internal_cost_cents||0)/100}); const ms=p.payment_plan?.next || p.payment_plan?.milestones?.at(-1); setDelivery(d=>({...d,milestone_id:ms?.id||''})); } catch(e){toast.error(e.message);} };
  const save = async () => { setBusy(true); try { const { internal_cost_yuan, ...payload }=form; await api.staffUpdateServiceProject(scope,selected.id,{...payload,internal_cost_cents:Math.round(Number(internal_cost_yuan||0)*100),expected_version:selected.version,eta_at:form.eta_at?Math.floor(new Date(form.eta_at).getTime()/1000):null,idempotency_key:crypto.randomUUID()}); toast.success('项目已更新'); await open(selected.id); await load(); } catch(e){toast.error(e.message);} finally{setBusy(false);} };
  const upload = async file => { if(!file)return; if(!delivery.version_label.trim()) { fileRef.current.value=''; return toast.warning('请先填写版本名称'); } setBusy(true); try { await api.staffUploadDeliverable(scope,selected.id,file,delivery); toast.success('交付文件已上传，历史版本已保留'); await open(selected.id); setDelivery(d=>({...d,version_label:'',description:'',is_preview:false})); } catch(e){toast.error(e.message);} finally{setBusy(false);if(fileRef.current)fileRef.current.value='';} };
  const plan=selected?.payment_plan;
  return <div className="mx-auto max-w-6xl px-6 py-8">
    <div className="flex items-end justify-between"><div><h1 className="text-xl font-bold text-ink">{readOnly?'人工服务履约全景':'服务履约工作台'}</h1><p className="mt-1 text-sm text-slate-500">按付款阶段上传预览稿和正式交付版本，所有历史版本均保留。</p></div><button className="btn-ghost text-xs" onClick={load}><Refresh className="h-4 w-4"/>刷新</button></div>
    <select className="input mt-5 w-48" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部状态</option>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select>
    <div className="mt-4 overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">项目号</th><th className="p-3">用户</th><th className="p-3">类型</th><th className="p-3">阶段</th><th className="p-3">进度</th></tr></thead><tbody>{list.map(p=><tr key={p.id} onClick={()=>open(p.id)} className="cursor-pointer border-t hover:bg-slate-50"><td className="p-3 font-mono text-xs">{p.project_no}</td><td className="p-3">{p.user_name}<div className="text-xs text-slate-400">{p.user_email}</div></td><td className="p-3">{p.service_type==='thesis_coaching'?'论文指导':'毕业作品'}</td><td className="p-3">{p.stage}</td><td className="p-3">{p.progress}%</td></tr>)}</tbody></table>{!list.length&&<div className="p-10 text-center text-sm text-slate-400">暂无服务项目</div>}</div>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl">
      <div className="flex justify-between"><div><h2 className="font-semibold text-ink">{selected.project_no}</h2><p className="text-xs text-slate-400">{selected.user_name} · {selected.user_email}</p></div><button className="btn-ghost" onClick={()=>setSelected(null)}>关闭</button></div>
      <fieldset disabled={readOnly} className="disabled:opacity-80"><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">状态<select className="input mt-1" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label><label className="text-sm">进度<input className="input mt-1" type="number" min="0" max="100" value={form.progress} onChange={e=>setForm({...form,progress:Number(e.target.value)})}/></label><label className="text-sm">当前阶段<input className="input mt-1" value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}/></label><label className="text-sm">预计完成时间<input className="input mt-1" type="datetime-local" value={form.eta_at} onChange={e=>setForm({...form,eta_at:e.target.value})}/></label><label className="text-sm sm:col-span-2">服务边界<textarea className="input mt-1" rows="2" value={form.scope_summary} onChange={e=>setForm({...form,scope_summary:e.target.value})}/></label><label className="text-sm">预计工时<input className="input mt-1" type="number" value={form.estimated_hours} onChange={e=>setForm({...form,estimated_hours:Number(e.target.value)})}/></label><label className="text-sm">实际工时<input className="input mt-1" type="number" value={form.actual_hours} onChange={e=>setForm({...form,actual_hours:Number(e.target.value)})}/></label><label className="text-sm">内部成本（元）<input className="input mt-1" type="number" value={form.internal_cost_yuan} onChange={e=>setForm({...form,internal_cost_yuan:Number(e.target.value)})}/></label></div><label className="mt-4 block text-sm">用户下一步动作<input className="input mt-1" value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})}/></label><label className="mt-4 block text-sm">用户可见说明<textarea className="input mt-1" rows="2" value={form.user_visible_note} onChange={e=>setForm({...form,user_visible_note:e.target.value})}/></label><label className="mt-4 block text-sm">内部备注<textarea className="input mt-1" rows="2" value={form.internal_note} onChange={e=>setForm({...form,internal_note:e.target.value})}/></label></fieldset>
      {plan?.milestones?.length>0&&<div className="mt-5 rounded-xl border border-slate-200 p-4"><h3 className="text-sm font-semibold">付款阶段</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{plan.milestones.map(m=><div key={m.id} className="flex justify-between rounded-lg bg-slate-50 px-3 py-2 text-xs"><span>{m.sequence}. {m.title}</span><span className={m.status==='paid'?'text-green-600':'text-slate-500'}>{money(m.amount_cents)} · {m.status==='paid'?'已付':'未付'}</span></div>)}</div></div>}
      <div className="mt-5 rounded-xl border border-accent-100 bg-accent-50/20 p-4"><h3 className="text-sm font-semibold text-ink">上传交付版本</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">关联付款阶段<select className="input mt-1" value={delivery.milestone_id} disabled={readOnly} onChange={e=>setDelivery({...delivery,milestone_id:e.target.value})}>{plan?.milestones?.map(m=><option key={m.id} value={m.id}>{m.sequence}. {m.title}（{m.status==='paid'?'已付':'未付'}）</option>)}</select></label><label className="text-sm">版本名称<input className="input mt-1" disabled={readOnly} value={delivery.version_label} onChange={e=>setDelivery({...delivery,version_label:e.target.value})} placeholder="如：初稿 V1、终稿 V3"/></label><label className="text-sm sm:col-span-2">版本说明<textarea className="input mt-1" rows="2" disabled={readOnly} value={delivery.description} onChange={e=>setDelivery({...delivery,description:e.target.value})} placeholder="说明本版新增、修改和交付内容"/></label></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" disabled={readOnly} checked={delivery.is_preview} onChange={e=>setDelivery({...delivery,is_preview:e.target.checked})}/>预览文件（对应阶段付款前也可下载）</label>{!readOnly&&<input ref={fileRef} type="file" className="mt-3 block w-full text-sm" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/>}<p className="mt-2 text-xs text-slate-500">正式文件仅在对应阶段付款后开放；上传同名文件也不会覆盖旧版本。</p></div>
      <div className="mt-5"><h3 className="text-sm font-semibold">已上传版本</h3><div className="mt-2 space-y-2">{selected.attachments.filter(a=>a.role==='deliverable').map(a=>{const m=plan?.milestones?.find(x=>x.id===a.milestone_id);return <div key={a.id} className="flex items-start gap-3 rounded-lg border p-3"><FileText className="mt-0.5 h-4 w-4 text-accent"/><div className="min-w-0 flex-1"><div className="text-sm font-medium">{a.version_label||a.original_name}</div><div className="text-xs text-slate-500">{m?`${m.sequence}. ${m.title}`:'未关联阶段'} · {a.is_preview?'付款前预览':'正式交付'} · {a.original_name}</div>{a.description&&<p className="mt-1 text-xs text-slate-600">{a.description}</p>}</div></div>})}{!selected.attachments.some(a=>a.role==='deliverable')&&<p className="text-sm text-slate-400">暂无交付版本</p>}</div></div>
      {!readOnly&&<div className="mt-5 flex justify-end"><button className="btn-primary" disabled={busy} onClick={save}><Check className="h-4 w-4"/>{busy?'保存中…':'保存项目'}</button></div>}
    </div></div>}
  </div>;
}

