import { useEffect, useRef, useState } from 'react';
import { api } from '../lib/api.js';
import { toast } from './Toast.jsx';
import { Check, Refresh } from './Icons.jsx';

const STATUS = [
  ['submitted','已提交'],['evaluating','评估中'],['awaiting_quote','待报价'],['awaiting_payment','待付款'],
  ['paid','已付款'],['in_progress','进行中'],['waiting_customer','待用户补充'],['pending_acceptance','待验收'],
  ['revision','修改中'],['completed','已完成'],['cancelled','已取消'],['refunded','已退款'],
];

export default function StaffServiceProjects({ scope }) {
  const fileRef = useRef(null); const [list, setList] = useState([]); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const [filter, setFilter] = useState('');
  const [form, setForm] = useState({ status:'', progress:0, stage:'', next_action:'', user_visible_note:'', internal_note:'', eta_at:'' });
  const load = async () => { try { setList((await api.staffListServiceProjects(scope, { status: filter })).projects || []); } catch(e) { toast.error(e.message); } };
  useEffect(() => { load(); }, [filter]);
  const open = async (id) => { try { const p=(await api.staffServiceProjectDetail(scope,id)).project; const date=p.eta_at?new Date(Number(p.eta_at)*1000):null; const offset=date?date.getTimezoneOffset()*60000:0; const eta=date?new Date(date.getTime()-offset).toISOString().slice(0,16):''; setSelected(p); setForm({status:p.status,progress:p.progress,stage:p.stage,next_action:p.next_action,user_visible_note:'',internal_note:p.internal_note||'',eta_at:eta}); } catch(e){toast.error(e.message);} };
  const save = async () => { setBusy(true); try { await api.staffUpdateServiceProject(scope, selected.id, {...form, expected_version:selected.version, eta_at:form.eta_at?Math.floor(new Date(form.eta_at).getTime()/1000):null, idempotency_key:crypto.randomUUID()}); toast.success('进度已更新并通知用户'); await open(selected.id); await load(); } catch(e){toast.error(e.message);} finally{setBusy(false);} };
  const upload = async(file)=>{if(!file)return;setBusy(true);try{await api.staffUploadDeliverable(scope,selected.id,file);toast.success('交付成果已上传');await open(selected.id);}catch(e){toast.error(e.message);}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}};
  return <div className="mx-auto max-w-6xl px-6 py-8"><div className="flex items-end justify-between"><div><h1 className="text-xl font-bold text-ink">服务履约工作台</h1><p className="mt-1 text-sm text-slate-500">更新用户可见进度、下一步动作，上传最终交付成果。</p></div><button className="btn-ghost text-xs" onClick={load}><Refresh className="h-4 w-4"/>刷新</button></div>
    <select className="input mt-5 w-48" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部状态</option>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select>
    <div className="mt-4 overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">项目号</th><th className="p-3">用户</th><th className="p-3">类型</th><th className="p-3">阶段</th><th className="p-3">进度</th><th className="p-3">推广码</th></tr></thead><tbody>{list.map(p=><tr key={p.id} onClick={()=>open(p.id)} className="cursor-pointer border-t hover:bg-slate-50"><td className="p-3 font-mono text-xs">{p.project_no}</td><td className="p-3">{p.user_name}<div className="text-xs text-slate-400">{p.user_email}</div></td><td className="p-3">{p.service_type==='thesis_coaching'?'论文指导':'毕业作品'}</td><td className="p-3">{p.stage}</td><td className="p-3">{p.progress}%</td><td className="p-3">{p.promotion_code_snapshot||'—'}</td></tr>)}</tbody></table>{!list.length&&<div className="p-10 text-center text-sm text-slate-400">暂无服务项目</div>}</div>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h2 className="font-semibold text-ink">{selected.project_no}</h2><p className="text-xs text-slate-400">{selected.user_name} · {selected.user_email}</p></div><button className="btn-ghost" onClick={()=>setSelected(null)}>关闭</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">状态<select className="input mt-1" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label><label className="text-sm">进度（0-100）<input className="input mt-1" type="number" min="0" max="100" value={form.progress} onChange={e=>setForm({...form,progress:Number(e.target.value)})}/></label><label className="text-sm">当前阶段<input className="input mt-1" value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}/></label><label className="text-sm">预计完成时间（选填）<input className="input mt-1" type="datetime-local" value={form.eta_at} onChange={e=>setForm({...form,eta_at:e.target.value})}/></label></div><label className="mt-4 block text-sm">用户下一步动作<input className="input mt-1" value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})}/></label><label className="mt-4 block text-sm">本次用户可见说明<textarea className="input mt-1" rows="3" value={form.user_visible_note} onChange={e=>setForm({...form,user_visible_note:e.target.value})}/></label><label className="mt-4 block text-sm">内部备注（用户不可见）<textarea className="input mt-1" rows="2" value={form.internal_note} onChange={e=>setForm({...form,internal_note:e.target.value})}/></label><div className="mt-5 flex items-center justify-between gap-3"><input ref={fileRef} type="file" className="text-sm" onChange={e=>upload(e.target.files?.[0])}/><button className="btn-primary" disabled={busy} onClick={save}><Check className="h-4 w-4"/>{busy?'保存中…':'保存进度'}</button></div></div></div>}
  </div>;
}
